version: "2"
run:
  # disallows implicit automatic updating of go.mod and fails when any changes to go.mod are needed
  modules-download-mode: readonly

linters:
  enable:
    - asciicheck
    - bidichk
    - durationcheck
    - errname
    - errorlint
    - govet
    - importas
    - ineffassign
    - misspell
    - nilerr
    - unconvert
    - nolintlint
  disable:
    # Revisit issues in the codebase with these linters
    # and re-enable
    - errcheck
    - staticcheck
    - unused

formatters:
  enable:
    - gofmt
    - goimports