name: Nominate a reviewer
description: Nomination for reviewer role.
title: 'Reviewer role for @'
labels: ["nomination"]
assignees:
  - oscal-sdk-go-maintainers
  - oscal-sdk-go-reviewers
body:
  - type: markdown
    attributes:
      value: |
        *Please review our [membership documentation](https://github.com/oscal-compass/community/blob/main/MEMBERSHIP.md) for more details.*
  - type: input
    validations:
      required: true
    attributes:
      label: GitHub username
      description: The GitHub username for the nominee
  - type: textarea
    validations:
      required: true
    attributes:
      label: Sponsors
      description: |
        List the GitHub usernames of the two project Maintainers who are sponsoring the application.
        The sponsors need to be contact ahead of the application.
      placeholder: |
        @sponsor1
        @sponsor2
  - type: textarea
    attributes:
      label: Contributions
      description: |
        Provide a list of contributions the nominee has made to the project or provide justification for role change.
